import type { Customer, Proposal, ProposalStatus, CommissionStatus } from './types';

export const customers: Omit<Customer, 'id' | 'ownerId'>[] = [
  {
    name: 'Ana Silva',
    cpf: '123.456.789-01',
    benefitNumber: '123456789',
    phone: '(11) 98765-4321',
    email: 'ana.silva@example.com',
    birthDate: '1965-03-15',
    observations: 'Cliente antiga, bom relacionamento.',
    cep: '01001-000',
    street: 'Praça da Sé',
    number: '100',
    complement: 'Lado A',
    neighborhood: 'Sé',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    name: 'Bruno Costa',
    cpf: '234.567.890-12',
    benefitNumber: '234567890',
    phone: '(21) 99876-5432',
    email: 'bruno.costa@example.com',
    birthDate: '1958-07-22',
    observations: 'Primeiro contato.',
    cep: '20040-004',
    street: 'Avenida Rio Branco',
    number: '156',
    complement: 'Sala 2001',
    neighborhood: 'Centro',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    name: 'Carla Dias',
    cpf: '345.678.901-23',
    benefitNumber: '345678901',
    phone: '(31) 98765-1234',
    email: 'carla.dias@example.com',
    birthDate: '1970-11-30',
    observations: 'Indicação de outro cliente.',
    cep: '30130-005',
    street: 'Avenida Afonso Pena',
    number: '1500',
    complement: '',
    neighborhood: 'Centro',
    city: 'Belo Horizonte',
    state: 'MG',
  },
  {
    name: 'Daniel Faria',
    cpf: '456.789.012-34',
    benefitNumber: '456789012',
    phone: '(41) 99876-4321',
    email: 'daniel.faria@example.com',
    birthDate: '1950-01-30',
    observations: 'Cliente com urgência na liberação do valor.',
    cep: '80020-320',
    street: 'Rua XV de Novembro',
    number: '500',
    complement: '',
    neighborhood: 'Centro',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    name: 'Elisa Gomes',
    cpf: '567.890.123-45',
    benefitNumber: '567890123',
    phone: '(51) 98765-5678',
    email: 'elisa.gomes@example.com',
    birthDate: '1949-05-10',
    observations: 'Cliente possui restrição no nome. Verificar condições.',
    cep: '90010-210',
    street: 'Rua dos Andradas',
    number: '1234',
    complement: 'Loja 5',
    neighborhood: 'Centro Histórico',
    city: 'Porto Alegre',
    state: 'RS',
  },
];


export const proposals: Omit<Proposal, 'id' | 'ownerId' | 'proposalNumber'>[] = [
    {
        customerId: '', // Placeholder, will be replaced with real customer ID
        product: 'Margem',
        table: 'Tabela Padrão',
        term: 84,
        installmentAmount: 550.75,
        netAmount: 22000.00,
        grossAmount: 25500.00,
        status: 'Em Andamento',
        approvingBody: 'INSS',
        commissionValue: 1275.00,
        commissionStatus: 'Pendente',
        commissionPercentage: 5,
        amountPaid: 0,
        promoter: 'Promotora A',
        bank: '237 - Bradesco S.A.',
        dateDigitized: new Date().toISOString(),
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Portabilidade',
        table: 'Portabilidade B',
        term: 84,
        installmentAmount: 320.00,
        netAmount: 15000.00,
        grossAmount: 17000.00,
        status: 'Aguardando Saldo',
        approvingBody: 'INSS',
        commissionValue: 935.00,
        commissionStatus: 'Pendente',
        commissionPercentage: 5.5,
        amountPaid: 0,
        promoter: 'Promotora B',
        bank: '341 - Itaú Unibanco S.A.',
        bankOrigin: '104 - Caixa Econômica Federal',
        dateDigitized: '2024-06-10T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Refin',
        table: 'Refin Padrão',
        term: 72,
        installmentAmount: 800.00,
        netAmount: 30000.00,
        grossAmount: 34000.00,
        status: 'Pago',
        approvingBody: 'INSS',
        commissionValue: 1700.00,
        commissionStatus: 'Paga',
        commissionPercentage: 5,
        amountPaid: 1700.00,
        promoter: 'Promotora A',
        bank: '001 - Banco do Brasil S.A.',
        dateDigitized: '2024-05-20T10:00:00.000Z',
        dateApproved: '2024-05-22T10:00:00.000Z',
        datePaidToClient: '2024-05-25T10:00:00.000Z',
        commissionPaymentDate: '2024-06-05T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Saque Complementar',
        table: 'Tabela Saque',
        term: 24,
        installmentAmount: 150.00,
        netAmount: 2500.00,
        grossAmount: 3000.00,
        status: 'Reprovado',
        approvingBody: 'SIAPE',
        commissionValue: 150.00,
        commissionStatus: 'Pendente',
        commissionPercentage: 5,
        amountPaid: 0,
        promoter: 'Promotora C',
        bank: '077 - Inter S.A.',
        dateDigitized: '2024-06-15T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Margem',
        table: 'Tabela Especial',
        term: 84,
        installmentAmount: 950.0,
        netAmount: 40000.0,
        grossAmount: 45000.0,
        status: 'Pendente',
        approvingBody: 'INSS',
        commissionValue: 2250.0,
        commissionStatus: 'Pendente',
        commissionPercentage: 5,
        amountPaid: 0,
        promoter: 'Promotora B',
        bank: '033 - Santander (Brasil) S.A.',
        dateDigitized: '2024-06-20T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Refin Port',
        table: 'Refin Port D',
        term: 84,
        installmentAmount: 400.0,
        netAmount: 18000.0,
        grossAmount: 20000.0,
        status: 'Saldo Pago',
        approvingBody: 'INSS',
        commissionValue: 1200.0,
        commissionStatus: 'Parcial',
        commissionPercentage: 6,
        amountPaid: 600,
        promoter: 'Promotora A',
        bank: '623 - PAN S.A.',
        bankOrigin: '237 - Bradesco S.A.',
        dateDigitized: '2024-05-05T10:00:00.000Z',
        commissionPaymentDate: '2024-06-10T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Margem',
        table: 'Tabela Padrão',
        term: 84,
        installmentAmount: 220.0,
        netAmount: 8000.0,
        grossAmount: 9500.0,
        status: 'Em Andamento',
        approvingBody: 'INSS',
        commissionValue: 475.0,
        commissionStatus: 'Pendente',
        commissionPercentage: 5,
        amountPaid: 0,
        promoter: 'Promotora C',
        bank: '707 - Daycoval S.A.',
        dateDigitized: '2024-06-25T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      },
      {
        customerId: '',
        product: 'Cartão com saque',
        table: 'Tabela Cartão',
        term: 84,
        installmentAmount: 100.0,
        netAmount: 2000.0,
        grossAmount: 2200.0,
        status: 'Pago',
        approvingBody: 'Federal',
        commissionValue: 110.0,
        commissionStatus: 'Paga',
        commissionPercentage: 5,
        amountPaid: 110.0,
        promoter: 'Promotora A',
        bank: '318 - BMG S.A.',
        dateDigitized: '2024-05-15T10:00:00.000Z',
        dateApproved: '2024-05-18T10:00:00.000Z',
        datePaidToClient: '2024-05-21T10:00:00.000Z',
        commissionPaymentDate: '2024-06-02T10:00:00.000Z',
        operator: "Fábio",
        commissionBase: 'gross',
      }
];
